# These are supported funding model platforms

github: ['darkiezZzz', 'haotogel-official', 'haotogel-livedraw', 'haotogel-assistant']
community_bridge: Haotogel-Official
custom: ['https://t.me/DarkiezZzz', 'https://t.me/HaotogelLivedraw']
